### ISSUE TITLE
Could not run controller: could not get configured server

### ISSUE THREAD

**Issue by yousafsyed-bg** [cbeneke/hcloud-fip-controller#35]
I am trying to deploy the latest FIP controller but it keeps giving me following error

``` bash
I0407 06:48:39.761347       1 leaderelection.go:235] attempting to acquire leader lease  fip-controller/fip...
I0407 06:49:15.701491       1 leaderelection.go:245] successfully acquired lease fip-controller/fip
time="2020-04-07T06:49:15Z" level=info msg="Started leading" func="github.com/sirupsen/logrus.(*Logger).Log" file="/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192"
time="2020-04-07T06:49:19Z" level=fatal msg="Could not run controller: could not get configured server: could not fetch servers: Get \"https://api.hetzner.cloud/v1/servers?page=1&per_page=50\": dial tcp: lookup api.hetzner.cloud on 10.43.0.10:53: server misbehaving" func="github.com/sirupsen/logrus.(*Entry).Logf" file="/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314"

```

I have tested that networking from other deployments, for example from Nginx-ingress pods I can do curl requests to the hetzner-cloud API with the same API-token and it works but for some reason, the FIP controller is failing on API requests.

Is this a bug ? or I have misconfigured something

**Update:**

Redeployed the cluster it worked

**Comment by cbeneke** [comment]
Hi, might be both, but the message `lookup api.hetzner.cloud on 10.43.0.10:53: server misbehaving` hints in the direction, that it's not a bug in the code but the DNS resolution on the fip-controller pod does not work.

Are the nginx-ingress and the fip-controller pods set up in a comparable manner (using the same network rules etc)? Could you validate (e.g. by running a pod with the fip-controller image and command /bin/bash) if the DNS resolution works fine in general?

**Comment by yousafsyed-bg** [comment]
Thanks for replying fast, I will try that report back

**Comment by cbeneke** [comment]
Hey @yousafsyed-bg do you have some further info on this? :)

**Comment by cbeneke** [comment]
Since this is stale for about a month now I'll close the issue. Please feel free to re-open in case the problem persists.
