### ISSUE TITLE
Could not run controller: could not get kubernetes node address

### ISSUE THREAD

**Issue by gans13** [cbeneke/hcloud-fip-controller#42]
Hi, I run the deployment on 3 nodes and get an error:

`level=info msg="Started leading" func="github.com/sirupsen/logrus.(*Logger).Log" file="/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192"
level=fatal msg="Could not run controller: could not get kubernetes node address: could not find address for node k8s-dev-node-3" func="github.com/sirupsen/logrus.(*Entry).Logf" file="/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314"
`

How can i fix it

**Comment by cbeneke** [comment]
Hi,

can you please include some information how you configured the controller? E.g. if used any of the following deployment types https://github.com/cbeneke/hcloud-fip-controller/blob/master/docs/deploy.md
Also please validate if your problem is already answered e.g. in #25 #30

**Comment by gans13** [comment]
Hi, I reconfigured the kubelet to private ip addresses, and set the node_address_type option to internal. And it worked. thank
