### ISSUE TITLE
required configuration options: 

### ISSUE THREAD

**Issue by PCatinean** [cbeneke/hcloud-fip-controller#45]
Hi and thanks for sharing this great tool.

I installed the controller using helm and all I see is `could not initialise controller: controller config invalid: required configuration options not configured: `

With nothing on the right side. I check the code and it should stack the errors and separate by comma yet nothing is there. Did you ever come across this?

Running Rancher k8s 1.17.5

**Comment by phiphi282** [comment]
After looking into the code, I found out that error message is constructed in a wrong way.

I will create a pull request shortly.
For now make sure that you have set HcloudApiToken and HcloudFloatingIPs in your config.

**Comment by PCatinean** [comment]
Thank you for the reply, I have set them and then all the others one by one just to try to get a different result but still nothing. Maybe I'm passing them the wrong way or something not sure...

**Comment by phiphi282** [comment]
Okay I have created a pull request for giving better error output.
For your problem.
The other 2 possible missing values that can produce the error message are NodeName and Namespace. 
Normally these are already set in the manifests but maybe you have changed them somehow (maybe an empty string for the namespace?).

If you really want to test this out now: I have pushed the image to phiphi282/hcloud-fip-controller:undefinedError1
I haven't tested it yet though. But considering the change was only one word I am pretty confident in that it works ;)

**Comment by cbeneke** [comment]
Reopening, since the error was only part of the described problem

**Comment by PCatinean** [comment]
Thank you for the support guys. I finally got the error message from the app which was "hetzner floating ips" are not defined. I found that strange because I clearly defined them as per the documentation but then when I manually created the configmap it suddenly started working.

As far as I can tell the only difference between the two (because I inspected both configmaps independently) can be traced to this https://github.com/cbeneke/helm-charts/blob/master/charts/hcloud-fip-controller/templates/config.yaml#L9

The documentation for the manual creation specifies config.json whereas the configmap from the helm chart has just config. Maybe this is issue?

**Comment by cbeneke** [comment]
Hi, yes I saw the change while working on https://github.com/cbeneke/helm-charts/pull/6
Will be fixed in the helm repo when I find the time to test the changes introduced in the PR

**Comment by cbeneke** [comment]
The PR was just merged, afaict it should now be working with using the helm-operator. I will close the ticket here now, if you encounter some further problems feel free to open another PR (preferably on the helm-charts repo for config errors, and here for bugs in the code :) )
