### ISSUE TITLE
find address for nodes by hostname/ ip of particular interface

### ISSUE THREAD

**Issue by ghorofamike** [cbeneke/hcloud-fip-controller#48]
I have  situation where there is a separate network connecting the nodes aside from that provided by the private network from hertzner. This is the network used by  --node-ip in init, this  therefore means that the node cant be found by
hcloud-controller-manager that uses this info to do things, therefore i have no EXTERNAL_IP on the node. [see this similar issue at hcloud-controller](https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/4#issue-297866568),  I can not use the 'internal'  type with this controller either since it will attempt to use my private network rather than hertzner s private net, is there a possibility to use a third option, such as  'hostname' or specifying an interface name to be queried for ips?

**Comment by phiphi282** [comment]
I may have an idea on how to fix this. Currently we just use the first ip address on a node, that has certain criteria. 
For your case to work, it would be possible to first get all matching ip addresses for a node and then try all those addresses against the hetzner api until we find the node or have tried all ips.
Since ips are unique in a cluster, this approach would always find the correct hetzner vm as well

There is currently a rather large pull request, that still needs some work, so I will create a pull request for this, only after the old one is merged.

**Comment by ghorofamike** [comment]
does #55  check against all IP's?  looks like it does not? this is a node i have with these IP's: 
Node: 
```
Private vpn:  172.18.6.4   ( network used by ks8, in --node-ip)
private hertzner   :  10.0.0.4   (this is not used by ks8)
```

But looks like this controller is still only searching through the IP's ks8 is using, ie those passed thru --node-ip, 
and cant find them using the API naturally on the hertzner addresslist,  here is an error log line: 

`time="2020-12-29T12:45:56Z" level=fatal msg="Could not run controller: Could not get server objects for addressList: Could not find an a server for ip '172.18.6.4'" func="github.com/sirupsen/logrus.(*Entry).Logf" file="/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314"`

**Comment by phiphi282** [comment]
The hostname does unfortunately not always match with the node name so we can't consistently match those.

Using the hcloud-cloud-controller-manager would make it consistenly but it also adds all ips from private networks that are connected to the instance as internal ips to the node.

Are you using the [hcloud-cloud-controller-manager](https://github.com/hetznercloud/hcloud-cloud-controller-manager) already?

**Comment by ghorofamike** [comment]
> The hostname does unfortunately not always match with the node name so we can't consistently match those.
> 
> Using the hcloud-cloud-controller-manager would make it consistenly but it also adds all ips from private networks that are connected to the instance as internal ips to the node.
> 
> Are you using the [hcloud-cloud-controller-manager](https://github.com/hetznercloud/hcloud-cloud-controller-manager) already?

i did install hcloud-cloud-controller-manager  on my ks8 cluster, but it also  has that same requirement that the network used by ks8 and the hertzner private network be the same so it can match with the api.  this is the reason i asked about future support for hostnames. this would provide an avenue for our use case. we have automatcally provisioned clusters with consistent names between the  api and the node names, so matching would be guaranteed.
