### ISSUE TITLE
floating_ips_label_selector has no Dokumentation and the (for me) obvious way did not work

### ISSUE THREAD

**Issue by dsteinberg111** [cbeneke/hcloud-fip-controller#57]
Since the old way to define the IPs is deprecated I tried to use the Label - Selector like this:
```apiVersion: v1
kind: ConfigMap
metadata:
  name: fip-controller-config
  namespace: fip-controller
data:
  config.json: |
    {
      "floating_ips_label_selector": "worker",

      "node_address_type": "external"
    }
```
Before that I used the Hetzner Interface to give all Ips I want to use the Label "worker". There are also IPs for the master, so I gave them the Label "master".
And that did not work; The "master" IPs where also changed. So Im asking;
How to Use this: floating_ips_label_selector

Thanks for the Help in advance.

David

**Comment by phiphi282** [comment]
The hetzner label selector is described here: https://docs.hetzner.cloud/#label-selector
I will definitely add the link in our documentation too.

I am not sure how the labels you created look exactly but it sounds like you configured it correctly if `worker` and `master` are both keys.
If you can't find a solution in that section I will try and replicate the issue myself later this week :)

Hope that helps

**Comment by phiphi282** [comment]
I will close this issue for now as there seem to be no more issues. Feel free to reopen the ticket if there are still some uncertainties.
