### ISSUE TITLE
Helm Repo offline

### ISSUE THREAD

**Issue by dsteinberg111** [cbeneke/hcloud-fip-controller#61]
The deploy.md refers to a helm repo that is no longer working. I suggest deleting that part leaving the manual deployment as only option or re-enable the repo.
kind regards

David

...Unable to get an update from the "cbeneke" chart repository (https://cbeneke.github.com/helm-charts):
	failed to fetch https://cbeneke.github.com/helm-charts/index.yaml : 404 Not Found

**Comment by rwunderer** [comment]
There's a typo in the documentation, the url is **github.io**, not github.com.

So it's actually:

```
$ helm repo add cbeneke https://cbeneke.github.io/helm-charts
$ helm repo update
```

**Comment by cbeneke** [comment]
Docs fixed in https://github.com/cbeneke/hcloud-fip-controller/pull/62 :)
